/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: ee70dbaff0720bdac3efb9cfe4028137)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	WORKER_SELF_REFERENCE: Fetcher /* guessthegame */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
